groups:
  - name: demo-service
    rules:
      - record: job:demo_request_latency_seconds_count:rate5m
        expr: sum by (job) (rate(demo_request_latency_seconds_count[5m]))

      - record: job:demo_requests_total:rate1m
        expr: sum by (job, method, endpoint) (rate(demo_requests_total[1m]))
